### ISSUE TITLE
Message correlation with variables doesn't work

### ISSUE THREAD

**Issue by Hari-Ritense** [valtimo-platform/valtimo-backend-libraries#1640]
**Expected behaviour**
correlationService.sendStartMessage("message_id", businessKey, variables)
correlationService.sendCatchEventMessage("message_id", businessKey, variables) and
correlationService.sendCatchEventMessageToAll("message_id", businessKey, variables)
should also make the variables (the third parameter) available in the target process.

**Current behaviour**
Message is sent and received but the variables are not available in the target process.

**Steps to reproduce**
- Create a process (two processes to check sendStartMessage) with message receive and send events.
- Create a variableMap in BPMN as input variable
- Include the variableMap in one of the above functions as the last parameter.
- Execute message send event.
- Check in the target process if the variables are available.

**Comment by ThomasMinkeRitense** [comment]
Duplicate: https://github.com/generiekzaakafhandelcomponent/gzac-issues/issues/81
